[package]
name = "portfolio"
version = "0.1.0"
authors = ["luizfgdo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webbrowser = "0.5.5"
actix-web = "3.3.2"
actix-files = "0.5.0"